apiVersion: 1

datasources:
  - name: InfluxDB
    uid: InfluxDB
    type: influxdb
    access: proxy
    url: http://127.0.0.1:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: solar
      defaultBucket: solar
      tlsSkipVerify: true
    secureJsonData:
      token: solar-token
